#!/bin/bash

# The MIT License
#
# Copyright (C) December 2021 Rizqi Nur Assyaufi <bandithijo@gmail.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# Deps:
# - power-profiles-daemon (powerprofilesctl)
# - dmenu
# - jq
# - dunst

LIST_PROFILES='''
[
["Performance", "High performance and power usage."],
["Balanced",    "Standard performance and power usage."],
["Power-saver", "Reduced performance and power usage."]
]
'''

EXPECT_PROFILES=$(echo ${LIST_PROFILES@L} | jq -r '.[][0]' | tr '\n' ' ')

profile_set() {
    for PROFILE in $EXPECT_PROFILES; do
        CHECK_PROFILE=$(powerprofilesctl list | grep $PROFILE | tr -d '* ')
        if [ ! -z $CHECK_PROFILE ]; then
            PROFILES+=$CHECK_PROFILE
        fi
    done

    SELECTED_PROFILE=$(echo ${PROFILES%?} | tr ':' '\n' | dmenu -i -p ' Select Profile')
    if [ ! -z $SELECTED_PROFILE ]; then
        powerprofilesctl set $SELECTED_PROFILE
        profile_notif
    fi
}

profile_get() {
    profile_notif
}

profile_notif() {
    GET_PROFILE=$(echo $(powerprofilesctl get))

    PROFILES_LENGTH=$(echo $LIST_PROFILES | jq length)
    for i in $(seq 0 $(($PROFILES_LENGTH - 1))); do
        EXPECT_PROFILES_SELECT=$(echo $EXPECT_PROFILES | cut -d' ' -f$((i + 1)))
        if [ $GET_PROFILE = $EXPECT_PROFILES_SELECT ]; then
            PROF_NAME=$(echo $LIST_PROFILES | jq -r --arg i $i '.[($i|tonumber)][0]')
            PROF_DESC=$(echo $LIST_PROFILES | jq -r --arg i $i '.[($i|tonumber)][1]')
        fi
    done

    dunstify "Power Profile: $PROF_NAME" "$PROF_DESC" -t 3000 -r 1
}

main() {
    OPTIONS='''
    [
    ["Get", "profile_get"],
    ["Set", "profile_set"]
    ]
    '''

    OBJ_MENU=$(echo $OPTIONS | jq -r '.[][0]' | dmenu -i -p ' Power Profiles')
    OBJ_SELECTED=$(echo $OPTIONS | jq -r ".[] | select(.[0] == \"$OBJ_MENU\") | .[1]")

    $OBJ_SELECTED
}

main
